FROM php:7.3-apache

WORKDIR /var/www/html

RUN apt-get update \
    &&  apt-get -y install tzdata cron \
    && a2enmod rewrite \
    && apt-get install -y --no-install-recommends libpq-dev libicu-dev libzip-dev zip unzip git cron \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo pdo_pgsql \
    && pecl install apcu xdebug \
    && docker-php-ext-enable apcu xdebug \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt update \
	&& apt -y install vim

# Configurando o timezone do servidor
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

#RUN apt-get -y remove tzdata
RUN rm -rf /var/cache/apk/*

# Create the log file to be able to run tail
RUN mkdir -p /var/log/cron

# Apache settings
COPY ./build/servico/000-default-servico.conf /etc/apache2/sites-available/000-default.conf

# COMPOSER
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY codigo-fonte/servico/ /var/www/html/
COPY build/servico/build.sh /usr/local/bin/build.sh

RUN chmod 777 -R /var/www/html/
RUN chmod 777 -R /usr/local/bin/build.sh

EXPOSE 80

CMD [ "sh", "-c", "/usr/local/bin/build.sh; /usr/local/bin/apache2-foreground; cron -f" ]